# Generated by Django 5.2.7 on 2025-11-15 01:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "PATIENT"),
                            ("DOCTOR", "DOCTOR"),
                            ("SYSTEM_ADMIN", "SYSTEM_ADMIN"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "analytics_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("metric_type", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("period", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
                "db_table": "analytics",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "medication_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("prescribed_date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "db_table": "medications",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_CONFIRMATION", "APPOINTMENT_CONFIRMATION"),
                            ("APPOINTMENT_REMINDER", "APPOINTMENT_REMINDER"),
                            ("TEST_RESULTS_AVAILABLE", "TEST_RESULTS_AVAILABLE"),
                            ("PRESCRIPTION_RENEWAL", "PRESCRIPTION_RENEWAL"),
                            ("HEALTH_ALERT", "HEALTH_ALERT"),
                            ("SYSTEM_MAINTENANCE", "SYSTEM_MAINTENANCE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("URGENT", "URGENT"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "report_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PATIENT_DEMOGRAPHICS", "PATIENT_DEMOGRAPHICS"),
                            ("DOCTOR_UTILIZATION", "DOCTOR_UTILIZATION"),
                            ("APPOINTMENT_STATISTICS", "APPOINTMENT_STATISTICS"),
                            ("REVENUE_ANALYSIS", "REVENUE_ANALYSIS"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.TextField()),
                ("generated_by", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "test_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("test_date", models.DateField(default=datetime.date.today)),
                ("results", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("normal_ranges", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Test Result",
                "verbose_name_plural": "Test Results",
                "db_table": "test_results",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "slot_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "db_table": "time_slots",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("doctor_id", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("specialty", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("department", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctors",
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("insurance_info", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="SystemAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("admin_id", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("access_level", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "System Admin",
                "verbose_name_plural": "System Admins",
                "db_table": "system_admins",
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "record_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("patient_id", models.CharField(max_length=100)),
                ("doctor_id", models.CharField(max_length=100)),
                ("visit_date", models.DateField(default=datetime.date.today)),
                ("diagnosis", models.TextField()),
                ("treatment_plan", models.TextField()),
                ("visit_type", models.CharField(max_length=100)),
                (
                    "medications",
                    models.ManyToManyField(
                        related_name="medical_records", to="core.medication"
                    ),
                ),
                (
                    "test_results",
                    models.ManyToManyField(
                        related_name="medical_records", to="core.testresult"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("doctor_id", models.CharField(max_length=100)),
                ("working_days", models.JSONField(default=list)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "available_slots",
                    models.ManyToManyField(
                        blank=True, related_name="schedules", to="core.timeslot"
                    ),
                ),
                (
                    "blocked_slots",
                    models.ManyToManyField(
                        blank=True, related_name="blocked_schedules", to="core.timeslot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "schedules",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("patient_id", models.CharField(max_length=100)),
                ("doctor_id", models.CharField(max_length=100)),
                ("appointment_date", models.DateTimeField()),
                ("specialty", models.CharField(max_length=100)),
                ("reason_for_visit", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.timeslot",
                    ),
                ),
            ],
        ),
    ]
