from enum import Enum


class UserType(Enum):
    PATIENT = "PATIENT"
    DOCTOR = "DOCTOR"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class Priority(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class NotificationType(Enum):
    APPOINTMENT_CONFIRMATION = "APPOINTMENT_CONFIRMATION"
    APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER"
    TEST_RESULTS_AVAILABLE = "TEST_RESULTS_AVAILABLE"
    PRESCRIPTION_RENEWAL = "PRESCRIPTION_RENEWAL"
    HEALTH_ALERT = "HEALTH_ALERT"
    SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE"


class AppointmentStatus(Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReportType(Enum):
    PATIENT_DEMOGRAPHICS = "PATIENT_DEMOGRAPHICS"
    DOCTOR_UTILIZATION = "DOCTOR_UTILIZATION"
    APPOINTMENT_STATISTICS = "APPOINTMENT_STATISTICS"
    REVENUE_ANALYSIS = "REVENUE_ANALYSIS"